### PR TITLE
Make POST /create/  endpoint accept `template` payload

### PR DESCRIPTION
**Pull request by gka**
Instead of creating a new visualization from the provided preset the route will fork an existing visualization.

- [x] call `/fork` route if a template id is provided
- [x] make sure users can only apply either `template` id or the raw presets (and not both)
- [x] finish and translate UI design for the confirmation page

### CODE REVIEW

**Comment by gka** [comment]
@lisacharlotterost @davidw-dw the confirmation page for forking a visualization will look slightly more friendly since at least we have a screenshot of the source visualization. Let me know if you have more questions or suggestions:
grafik

**Comment by davidw-dw** [comment]
@gka thanks for the pr. is there a chance to easily get that confirmation page on a local instance? i checked out `feature/chart-templates` branch on `datawrapper/frontend`.

**Comment by gka** [comment]
sure, but you need to generate that POST request somehow, a html form like this should do the trick:
```html
<form action="http://app.datawrapper.local/create/" method="POST">
    <input type="hidden" name="template" value="ABCDE" />
    <input type="submit" />
</form>

**Comment by davidw-dw** [comment]
Ok, i was trying to suggest style changes on my own, but due to the new setup / or general lack of knowledge where to style what best and in order to speed things up, here is my suggestion as a screenshot: 
Screenshot 2021-05-07 at 18 29 24
These are the changes:
- `p-6` (or a lot more) padding on the box
- `font-weight: 500` for title and buttons
- `mr-5` (or a lot more) padding on the left button

**Review by davidkokkelink — APPROVED** [review]

**Pull request merged**
