### PR TITLE
Add schema for preview querystrings

### PR DESCRIPTION
**Pull request by davidkokkelink**

### CODE REVIEW

**Comment by davidkokkelink** [comment]
Pretty sure there are a few more (cc @gka @elanals) - didn't we add a search prefill for tables? Maybe other stuff too?

**Comment by davidkokkelink** [comment]
There probably is no use-case for the prefill on the preview endpoint though apart from testing

**Comment by gka** [comment]
and `svgonly`!

**Comment by davidkokkelink** [comment]
and `map2svg` for the locators

**Comment by gka** [comment]
I am looking into the production log file now, spotted another parameter `fitheight=1`

**Review by gka — CHANGES_REQUESTED** [review]
Also I recommend you either define the `fakeBoolean` pseudo-type
```js
const fakeBoolean = _default => {
    const bool = Joi.boolean();
    const num = Joi.number().valid(0, 1);
    if (_default !== undefined) {
        bool.default(_default);
        num.default(_default ? 1 : 0);
    }
    return Joi.alternatives().try(bool, num);
};
```
or import it via
```js
import { fakeBoolean } from '@datawrapper/schemas/themeData/shared'
```
instead of of re-defining the `Joi.alternative()` over and over.
Also I don't see why `?transparent` shouldn't allow the 0|1 boolean as well.

**Comment by gka** [comment]
arguably, we could also move the `fakeBoolean` type to `'@datawrapper/schemas/shared` and maybe find a better name (e.g. numericBoolean)

**Comment by gka** [comment]
Here's the result of several hours of tracking every GET parameter used in our `/preview` route. Looks like we have everything covered now.

```js
{
  static: 58324,
  ott: 57657,
  plain: 36136,
  fitchart: 25960,
  fitheight: 3482,
  svgonly: 802,
  published: 58,
  transparent: 46,
  theme: 18,
  map2svg: 16
}
```
``

**Comment by davidkokkelink** [comment]
thanks for checking, i added the requested changes

**Review by gka — APPROVED** [review]
nice, thx

**Pull request merged**
